apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  labels:
  {{- include "oauth2-proxy.labels" . | nindent 4 }}
data:
  oauth2-proxy.cfg: |
    {{- .Values.config | nindent 4 }}
  {{- if .Values.authenticatedEmails }}
  authenticated-emails.txt: |
    {{- range $e := .Values.authenticatedEmails }}
    {{- $e | nindent 4 }}
    {{- end }}
    {{- end }}
