apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  labels:
  {{- include "oauth2-proxy.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: |
    {{- $value | toJson | nindent 4 }}
  {{- end }}
  {{- if .Values.authenticatedEmails }}
  __authenticated_emails: |
    {{- range $e := .Values.authenticatedEmails }}
    {{- $e | nindent 4 }}
    {{- end }}
  {{- end }}
