apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  labels:
  {{- include "oauth2-proxy.labels" . | nindent 4 }}
data:
  {{- .Values.config | toYaml | nindent 2 }}
  {{- if .Values.authenticatedEmails -}}
  __authenticated_emails: |
    {{ .Values.authenticatedEmails | nindent 4 }}
    {{- end }}
